### ISSUE TITLE
demo: improve examples and styling

### ISSUE THREAD

**Issue by christophercr** [NationalBankBelgium/ngx-form-errors#6]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/ngx-form-errors/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The Demo app is very basic and without styling.

## Expected behavior
The Demo should have a very nice look and feel and show all the features provided by the library.

## What is the motivation / use case for changing the behavior?
Fully working Demo app that catches the attention of the developer focusing on the added value of the library.

## Environment

<pre><code>
NgxFormErrors version: 1.0.0-alpha

</code></pre>

**Comment by christophercr** [comment]
@cnomes I have improved the demo app of this library. Unfortunately I've spent a lot of time in doing it because of some weird issues I had until I've managed to fix them. So... could I ask you a favor? Could you help me to improve the styling so that it looks nice for the demo of today?

The final demo is on this branch: `feature/demo-improvements`... thanks a lot!

**Comment by cnomes** [comment]
@christophercr, sure thing. I'll have a look at it. 👍
